/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * OpenPark - Hub Server
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { mutationInstance } from '../services/api';
export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface LotOut {
  id: string;
  name: string;
  address: string;
  total_spaces: number;
  available_spaces: number;
  base_fee: number;
  base_duration_minutes: number;
  extra_fee_per_unit: number;
  extra_fee_unit_minutes: number;
  latitude: number;
  longitude: number;
  daily_max_fee: number | null;
  created_at: string;
  updated_at: string;
}

/**
 * @summary List Lots
 */
export const listLotsApiV1LotsGet = (

 signal?: AbortSignal
) => {


      return mutationInstance<LotOut[]>(
      {url: `/api/v1/lots`, method: 'GET', signal
    },
      );
    }




export const getListLotsApiV1LotsGetQueryKey = () => {
    return [
    `/api/v1/lots`
    ] as const;
    }


export const getListLotsApiV1LotsGetQueryOptions = <TData = Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListLotsApiV1LotsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>> = ({ signal }) => listLotsApiV1LotsGet(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListLotsApiV1LotsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>>
export type ListLotsApiV1LotsGetQueryError = unknown


export function useListLotsApiV1LotsGet<TData = Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLotsApiV1LotsGet>>,
          TError,
          Awaited<ReturnType<typeof listLotsApiV1LotsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLotsApiV1LotsGet<TData = Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLotsApiV1LotsGet>>,
          TError,
          Awaited<ReturnType<typeof listLotsApiV1LotsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLotsApiV1LotsGet<TData = Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Lots
 */

export function useListLotsApiV1LotsGet<TData = Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLotsApiV1LotsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListLotsApiV1LotsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Get Lot
 */
export const getLotApiV1LotsLotIdGet = (
    lotId: string,
 signal?: AbortSignal
) => {


      return mutationInstance<LotOut>(
      {url: `/api/v1/lots/${lotId}`, method: 'GET', signal
    },
      );
    }




export const getGetLotApiV1LotsLotIdGetQueryKey = (lotId: string,) => {
    return [
    `/api/v1/lots/${lotId}`
    ] as const;
    }


export const getGetLotApiV1LotsLotIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError = HTTPValidationError>(lotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLotApiV1LotsLotIdGetQueryKey(lotId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>> = ({ signal }) => getLotApiV1LotsLotIdGet(lotId, signal);





   return  { queryKey, queryFn, enabled: lotId !== null && lotId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLotApiV1LotsLotIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>>
export type GetLotApiV1LotsLotIdGetQueryError = HTTPValidationError


export function useGetLotApiV1LotsLotIdGet<TData = Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError = HTTPValidationError>(
 lotId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>,
          TError,
          Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLotApiV1LotsLotIdGet<TData = Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError = HTTPValidationError>(
 lotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>,
          TError,
          Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLotApiV1LotsLotIdGet<TData = Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError = HTTPValidationError>(
 lotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Lot
 */

export function useGetLotApiV1LotsLotIdGet<TData = Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError = HTTPValidationError>(
 lotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLotApiV1LotsLotIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLotApiV1LotsLotIdGetQueryOptions(lotId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
